// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "netmessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace wowboss {

namespace {

const ::google::protobuf::Descriptor* NMHello_SYN_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  NMHello_SYN_reflection_ = NULL;
const ::google::protobuf::Descriptor* NMHello_ACK_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  NMHello_ACK_reflection_ = NULL;
const ::google::protobuf::Descriptor* NetMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  NetMessage_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* NetMessage_MessageType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_netmessage_2eproto() {
  protobuf_AddDesc_netmessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "netmessage.proto");
  GOOGLE_CHECK(file != NULL);
  NMHello_SYN_descriptor_ = file->message_type(0);
  static const int NMHello_SYN_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NMHello_SYN, version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NMHello_SYN, username_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NMHello_SYN, password_),
  };
  NMHello_SYN_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      NMHello_SYN_descriptor_,
      NMHello_SYN::default_instance_,
      NMHello_SYN_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NMHello_SYN, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NMHello_SYN, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(NMHello_SYN));
  NMHello_ACK_descriptor_ = file->message_type(1);
  static const int NMHello_ACK_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NMHello_ACK, version_ok_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NMHello_ACK, username_ok_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NMHello_ACK, password_ok_),
  };
  NMHello_ACK_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      NMHello_ACK_descriptor_,
      NMHello_ACK::default_instance_,
      NMHello_ACK_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NMHello_ACK, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NMHello_ACK, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(NMHello_ACK));
  NetMessage_descriptor_ = file->message_type(2);
  static const int NetMessage_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NetMessage, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NetMessage, hello_syn_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NetMessage, hello_ack_),
  };
  NetMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      NetMessage_descriptor_,
      NetMessage::default_instance_,
      NetMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NetMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NetMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(NetMessage));
  NetMessage_MessageType_descriptor_ = NetMessage_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_netmessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    NMHello_SYN_descriptor_, &NMHello_SYN::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    NMHello_ACK_descriptor_, &NMHello_ACK::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    NetMessage_descriptor_, &NetMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_netmessage_2eproto() {
  delete NMHello_SYN::default_instance_;
  delete NMHello_SYN_reflection_;
  delete NMHello_ACK::default_instance_;
  delete NMHello_ACK_reflection_;
  delete NetMessage::default_instance_;
  delete NetMessage_reflection_;
}

void protobuf_AddDesc_netmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020netmessage.proto\022\007wowboss\"B\n\013NMHello_S"
    "YN\022\017\n\007version\030\001 \002(\005\022\020\n\010username\030\002 \002(\t\022\020\n"
    "\010password\030\003 \002(\t\"K\n\013NMHello_ACK\022\022\n\nversio"
    "n_ok\030\001 \002(\010\022\023\n\013username_ok\030\002 \002(\010\022\023\n\013passw"
    "ord_ok\030\003 \002(\010\"\270\001\n\nNetMessage\022+\n\002id\030\001 \002(\0162"
    "\037.wowboss.NetMessage.MessageType\022\'\n\thell"
    "o_syn\030\002 \001(\0132\024.wowboss.NMHello_SYN\022\'\n\thel"
    "lo_ack\030\003 \001(\0132\024.wowboss.NMHello_ACK\"+\n\013Me"
    "ssageType\022\r\n\tHELLO_SYN\020\000\022\r\n\tHELLO_ACK\020\001", 359);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "netmessage.proto", &protobuf_RegisterTypes);
  NMHello_SYN::default_instance_ = new NMHello_SYN();
  NMHello_ACK::default_instance_ = new NMHello_ACK();
  NetMessage::default_instance_ = new NetMessage();
  NMHello_SYN::default_instance_->InitAsDefaultInstance();
  NMHello_ACK::default_instance_->InitAsDefaultInstance();
  NetMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_netmessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_netmessage_2eproto {
  StaticDescriptorInitializer_netmessage_2eproto() {
    protobuf_AddDesc_netmessage_2eproto();
  }
} static_descriptor_initializer_netmessage_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int NMHello_SYN::kVersionFieldNumber;
const int NMHello_SYN::kUsernameFieldNumber;
const int NMHello_SYN::kPasswordFieldNumber;
#endif  // !_MSC_VER

NMHello_SYN::NMHello_SYN()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void NMHello_SYN::InitAsDefaultInstance() {
}

NMHello_SYN::NMHello_SYN(const NMHello_SYN& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void NMHello_SYN::SharedCtor() {
  _cached_size_ = 0;
  version_ = 0;
  username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

NMHello_SYN::~NMHello_SYN() {
  SharedDtor();
}

void NMHello_SYN::SharedDtor() {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    delete username_;
  }
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    delete password_;
  }
  if (this != default_instance_) {
  }
}

void NMHello_SYN::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NMHello_SYN::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NMHello_SYN_descriptor_;
}

const NMHello_SYN& NMHello_SYN::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_netmessage_2eproto();  return *default_instance_;
}

NMHello_SYN* NMHello_SYN::default_instance_ = NULL;

NMHello_SYN* NMHello_SYN::New() const {
  return new NMHello_SYN;
}

void NMHello_SYN::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    version_ = 0;
    if (has_username()) {
      if (username_ != &::google::protobuf::internal::kEmptyString) {
        username_->clear();
      }
    }
    if (has_password()) {
      if (password_ != &::google::protobuf::internal::kEmptyString) {
        password_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool NMHello_SYN::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 version = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &version_)));
          set_has_version();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_username;
        break;
      }
      
      // required string username = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_username:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->username().data(), this->username().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_password;
        break;
      }
      
      // required string password = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_password:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->password().data(), this->password().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void NMHello_SYN::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 version = 1;
  if (has_version()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->version(), output);
  }
  
  // required string username = 2;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->username(), output);
  }
  
  // required string password = 3;
  if (has_password()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->password(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* NMHello_SYN::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 version = 1;
  if (has_version()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->version(), target);
  }
  
  // required string username = 2;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->username(), target);
  }
  
  // required string password = 3;
  if (has_password()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->password(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int NMHello_SYN::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 version = 1;
    if (has_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->version());
    }
    
    // required string username = 2;
    if (has_username()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->username());
    }
    
    // required string password = 3;
    if (has_password()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->password());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NMHello_SYN::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const NMHello_SYN* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const NMHello_SYN*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void NMHello_SYN::MergeFrom(const NMHello_SYN& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_version()) {
      set_version(from.version());
    }
    if (from.has_username()) {
      set_username(from.username());
    }
    if (from.has_password()) {
      set_password(from.password());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void NMHello_SYN::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NMHello_SYN::CopyFrom(const NMHello_SYN& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NMHello_SYN::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  
  return true;
}

void NMHello_SYN::Swap(NMHello_SYN* other) {
  if (other != this) {
    std::swap(version_, other->version_);
    std::swap(username_, other->username_);
    std::swap(password_, other->password_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata NMHello_SYN::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = NMHello_SYN_descriptor_;
  metadata.reflection = NMHello_SYN_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int NMHello_ACK::kVersionOkFieldNumber;
const int NMHello_ACK::kUsernameOkFieldNumber;
const int NMHello_ACK::kPasswordOkFieldNumber;
#endif  // !_MSC_VER

NMHello_ACK::NMHello_ACK()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void NMHello_ACK::InitAsDefaultInstance() {
}

NMHello_ACK::NMHello_ACK(const NMHello_ACK& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void NMHello_ACK::SharedCtor() {
  _cached_size_ = 0;
  version_ok_ = false;
  username_ok_ = false;
  password_ok_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

NMHello_ACK::~NMHello_ACK() {
  SharedDtor();
}

void NMHello_ACK::SharedDtor() {
  if (this != default_instance_) {
  }
}

void NMHello_ACK::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NMHello_ACK::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NMHello_ACK_descriptor_;
}

const NMHello_ACK& NMHello_ACK::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_netmessage_2eproto();  return *default_instance_;
}

NMHello_ACK* NMHello_ACK::default_instance_ = NULL;

NMHello_ACK* NMHello_ACK::New() const {
  return new NMHello_ACK;
}

void NMHello_ACK::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    version_ok_ = false;
    username_ok_ = false;
    password_ok_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool NMHello_ACK::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool version_ok = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &version_ok_)));
          set_has_version_ok();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_username_ok;
        break;
      }
      
      // required bool username_ok = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_username_ok:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &username_ok_)));
          set_has_username_ok();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_password_ok;
        break;
      }
      
      // required bool password_ok = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_password_ok:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &password_ok_)));
          set_has_password_ok();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void NMHello_ACK::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bool version_ok = 1;
  if (has_version_ok()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->version_ok(), output);
  }
  
  // required bool username_ok = 2;
  if (has_username_ok()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->username_ok(), output);
  }
  
  // required bool password_ok = 3;
  if (has_password_ok()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->password_ok(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* NMHello_ACK::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bool version_ok = 1;
  if (has_version_ok()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->version_ok(), target);
  }
  
  // required bool username_ok = 2;
  if (has_username_ok()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->username_ok(), target);
  }
  
  // required bool password_ok = 3;
  if (has_password_ok()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->password_ok(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int NMHello_ACK::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bool version_ok = 1;
    if (has_version_ok()) {
      total_size += 1 + 1;
    }
    
    // required bool username_ok = 2;
    if (has_username_ok()) {
      total_size += 1 + 1;
    }
    
    // required bool password_ok = 3;
    if (has_password_ok()) {
      total_size += 1 + 1;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NMHello_ACK::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const NMHello_ACK* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const NMHello_ACK*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void NMHello_ACK::MergeFrom(const NMHello_ACK& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_version_ok()) {
      set_version_ok(from.version_ok());
    }
    if (from.has_username_ok()) {
      set_username_ok(from.username_ok());
    }
    if (from.has_password_ok()) {
      set_password_ok(from.password_ok());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void NMHello_ACK::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NMHello_ACK::CopyFrom(const NMHello_ACK& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NMHello_ACK::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  
  return true;
}

void NMHello_ACK::Swap(NMHello_ACK* other) {
  if (other != this) {
    std::swap(version_ok_, other->version_ok_);
    std::swap(username_ok_, other->username_ok_);
    std::swap(password_ok_, other->password_ok_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata NMHello_ACK::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = NMHello_ACK_descriptor_;
  metadata.reflection = NMHello_ACK_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* NetMessage_MessageType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NetMessage_MessageType_descriptor_;
}
bool NetMessage_MessageType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const NetMessage_MessageType NetMessage::HELLO_SYN;
const NetMessage_MessageType NetMessage::HELLO_ACK;
const NetMessage_MessageType NetMessage::MessageType_MIN;
const NetMessage_MessageType NetMessage::MessageType_MAX;
const int NetMessage::MessageType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int NetMessage::kIdFieldNumber;
const int NetMessage::kHelloSynFieldNumber;
const int NetMessage::kHelloAckFieldNumber;
#endif  // !_MSC_VER

NetMessage::NetMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void NetMessage::InitAsDefaultInstance() {
  hello_syn_ = const_cast< ::wowboss::NMHello_SYN*>(&::wowboss::NMHello_SYN::default_instance());
  hello_ack_ = const_cast< ::wowboss::NMHello_ACK*>(&::wowboss::NMHello_ACK::default_instance());
}

NetMessage::NetMessage(const NetMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void NetMessage::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  hello_syn_ = NULL;
  hello_ack_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

NetMessage::~NetMessage() {
  SharedDtor();
}

void NetMessage::SharedDtor() {
  if (this != default_instance_) {
    delete hello_syn_;
    delete hello_ack_;
  }
}

void NetMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NetMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NetMessage_descriptor_;
}

const NetMessage& NetMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_netmessage_2eproto();  return *default_instance_;
}

NetMessage* NetMessage::default_instance_ = NULL;

NetMessage* NetMessage::New() const {
  return new NetMessage;
}

void NetMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0;
    if (has_hello_syn()) {
      if (hello_syn_ != NULL) hello_syn_->::wowboss::NMHello_SYN::Clear();
    }
    if (has_hello_ack()) {
      if (hello_ack_ != NULL) hello_ack_->::wowboss::NMHello_ACK::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool NetMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .wowboss.NetMessage.MessageType id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::wowboss::NetMessage_MessageType_IsValid(value)) {
            set_id(static_cast< ::wowboss::NetMessage_MessageType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_hello_syn;
        break;
      }
      
      // optional .wowboss.NMHello_SYN hello_syn = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_hello_syn:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_hello_syn()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_hello_ack;
        break;
      }
      
      // optional .wowboss.NMHello_ACK hello_ack = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_hello_ack:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_hello_ack()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void NetMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .wowboss.NetMessage.MessageType id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->id(), output);
  }
  
  // optional .wowboss.NMHello_SYN hello_syn = 2;
  if (has_hello_syn()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->hello_syn(), output);
  }
  
  // optional .wowboss.NMHello_ACK hello_ack = 3;
  if (has_hello_ack()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->hello_ack(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* NetMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .wowboss.NetMessage.MessageType id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->id(), target);
  }
  
  // optional .wowboss.NMHello_SYN hello_syn = 2;
  if (has_hello_syn()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->hello_syn(), target);
  }
  
  // optional .wowboss.NMHello_ACK hello_ack = 3;
  if (has_hello_ack()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->hello_ack(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int NetMessage::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .wowboss.NetMessage.MessageType id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->id());
    }
    
    // optional .wowboss.NMHello_SYN hello_syn = 2;
    if (has_hello_syn()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->hello_syn());
    }
    
    // optional .wowboss.NMHello_ACK hello_ack = 3;
    if (has_hello_ack()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->hello_ack());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NetMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const NetMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const NetMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void NetMessage::MergeFrom(const NetMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_hello_syn()) {
      mutable_hello_syn()->::wowboss::NMHello_SYN::MergeFrom(from.hello_syn());
    }
    if (from.has_hello_ack()) {
      mutable_hello_ack()->::wowboss::NMHello_ACK::MergeFrom(from.hello_ack());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void NetMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NetMessage::CopyFrom(const NetMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NetMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  if (has_hello_syn()) {
    if (!this->hello_syn().IsInitialized()) return false;
  }
  if (has_hello_ack()) {
    if (!this->hello_ack().IsInitialized()) return false;
  }
  return true;
}

void NetMessage::Swap(NetMessage* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(hello_syn_, other->hello_syn_);
    std::swap(hello_ack_, other->hello_ack_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata NetMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = NetMessage_descriptor_;
  metadata.reflection = NetMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace wowboss

// @@protoc_insertion_point(global_scope)
